### ISSUE TITLE
Update to a more recent release of fluentbit.

### ISSUE THREAD

**Issue by SeanWally2** [newrelic/newrelic-fluent-bit-output#102]
Is there a plan to update the version of fluentbit from 1.8.1 to a more recent release?

We are encountering some issues related to multiline parsing ( outlined in this issue - https://github.com/fluent/fluent-bit/issues/3886 ) that have been resolved in Fluentbit 1.8.9.

**Comment by noly** [comment]
Hi @SeanWally2, thanks for reaching out. 

We are in process to update all our fluent-bit dependencies to version >1.8.11. We expect to be done this week 😸

**Comment by noly** [comment]
More details in #104
