### ISSUE TITLE
Refresh Kubernetes service account tokens automatically

### ISSUE THREAD

**Issue by sdickhoven** [newrelic/newrelic-fluent-bit-output#110]
see https://github.com/fluent/fluent-bit/issues/5445

the [newrelic-logging](https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-logging) daemonset will stop functioning within 90d in eks if this is not fixed.

**Comment by gugacavalieri** [comment]
Looks like this issue was fixed on Fluent-bit 1.9.4: https://github.com/fluent/fluent-bit/issues/5445#issuecomment-1148033916

Any plans on upgrading the NewRelic image to use that new version?

**Comment by gugacavalieri** [comment]
https://github.com/newrelic/newrelic-fluent-bit-output/pull/114 should fix it 😄

**Comment by danybmx** [comment]
Indeed, @gugacavalieri, it should have been fixed, thanks for reporting!
