### ISSUE TITLE
Release 1.17.0 Issue With Plugin

### ISSUE THREAD

**Issue by Aniket-Singla** [newrelic/newrelic-fluent-bit-output#133]
```
[proxy] error opening plugin /fluent-bit/bin/out_newrelic.so: '/lib64/libc.so.6: version `GLIBC_2.32' not found (required by /fluent-bit/bin/out_newrelic.so)'
```

I have reverted back to 1.16.0 and it works. Please check the latest release which is causing the above issue.

**Comment by mrwillis** [comment]
We were pegged to the latest version hosted in ECR and this basically broke all of our services in production.

**Comment by guohaolee** [comment]
same, this broke all our ECS tasks.

**Comment by guohaolee** [comment]
Can you please rollback the working version to tagged as latest please?

**Comment by tomazellifelipe** [comment]
same, this broke all our ECS tasks.

**Comment by danybmx** [comment]
Hi deploying the rollback in 1.17.1, should be available soon. I let you know here.

**Comment by danybmx** [comment]
Hi again, the workflow is still running for windows images but the 1.17.1 is already available.

**Comment by danybmx** [comment]
The rollback should have fixed the issue, closing the ticket
