### ISSUE TITLE
Latest version (v1.17.0) of newrelic-fluent-bit-output image: broken GLIBC_2.32

### ISSUE THREAD

**Issue by c-t-disher** [newrelic/newrelic-fluent-bit-output#136]
ECS container builds are failing with the error message:

`[proxy] error opening plugin /fluent-bit/bin/out_newrelic.so: '/lib64/libc.so.6: version 'GLIBC_2.32' not found (required by /fluent-bit/bin/out_newrelic.so)'`

`[2023/06/14 19:28:41] [error] [plugin] error loading proxy plugin: /fluent-bit/bin/out_newrelic.so`

Since pulling the `logging-firelens-fluentbit` image with the `latest` version tag is the default behavior, this has the potential to crash production containers that restart for any reason.

Bug originally reported here -> https://forum.newrelic.com/s/hubtopic/aAX8W0000015B3pWAE/latest-version-v1170-of-newrelicfluentbitoutput-image-broken-glibc232

**Comment by danybmx** [comment]
Hi @c-t-disher version 1.17.1 is released and set at latest, it should work.
