### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by xaque208** [newrelic/newrelic-fluent-bit-output#21]

**Comment by jsubirat** [comment]
Hi @xaque208 ,

We have tags for each published release:

<img width="469" alt="Screen Shot 2020-06-30 at 7 11 25 PM" src="https://user-images.githubusercontent.com/6243832/86155975-817e7380-bb05-11ea-9a44-d9590314a75a.png">

I guess we can safely close this ticket, then. Please answer back or create a new one in case I missed something.

**Comment by xaque208** [comment]
Yes thanks @jsubirat.
