### ISSUE TITLE
Exclude Logs

### ISSUE THREAD

**Issue by Jlaird** [newrelic/newrelic-fluent-bit-output#22]
Is there a way to exclude containers or pods logs? I don't want all the Nginx access logs.

**Comment by bmcfeely** [comment]
@Jlaird You bet! You can add your own filters to the Fluent Bit pipeline: https://docs.fluentbit.io/manual/v/1.3/filter. Our output plugin just takes whatever comes out of the end of that pipeline and sends it to New Relic. 

So you'll need to configure what you want Fluent Bit to drop in a `[FILTER]` section of the Fluent Bit conf file (you might also do some parsing to get at attributes that you'll filter on: https://docs.fluentbit.io/manual/v/1.3/parser)
