### ISSUE TITLE
Release debug image based on fluent-bit:1.x.x-debug

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/newrelic-fluent-bit-output#27]
Since there is no shell, it's super difficult to debug in the container when something is not working.
Could you build and release a debug tag based on fluent-bit:1.x.x-debug image?
https://github.com/fluent/fluent-bit-docker-image/issues/19

**Comment by Noly** [comment]
Hi @tanaka-takayoshi thanks for submitting this issue, since [newrelic-fluent-bit-output-1.6.0](https://github.com/newrelic/newrelic-fluent-bit-output/releases/tag/v1.6.0) we've added support for `-debug` images:
You can use it `docker pull newrelic/newrelic-fluentbit-output:1.6.0-debug`
