### ISSUE TITLE
Request - Add proxy support.

### ISSUE THREAD

**Issue by tetsushiawano** [newrelic/newrelic-fluent-bit-output#28]
We need to use proxy to send output outside of our network.
I check code but it seems it doesn't have configurable proxy.
```
//export FLBPluginInit
func FLBPluginInit(ctx unsafe.Pointer) int {
	var config PluginConfig
	// Example to retrieve an optional configuration parameter
	config.endpoint = output.FLBPluginConfigKey(ctx, "endpoint")
	if len(config.endpoint) == 0 {
		config.endpoint = "https://log-api.newrelic.com/log/v1"
	}
	config.licenseKey = output.FLBPluginConfigKey(ctx, "licenseKey")
	config.apiKey = output.FLBPluginConfigKey(ctx, "apiKey")

	if len(config.apiKey) == 0 && len(config.licenseKey) == 0 {
		log.Print("[ERROR] either apiKey or licenseKey must be specified")
		return output.FLB_ERROR
	}

	if len(config.apiKey) > 0 && len(config.licenseKey) > 0 {
		log.Print("[ERROR] only one of apiKey or licenseKey can be specified")
		return output.FLB_ERROR
	}

	config.useApiKey = len(config.apiKey) > 0

	possibleeMaxBufferSize := output.FLBPluginConfigKey(ctx, "maxBufferSize")
	if len(possibleeMaxBufferSize) == 0 {
		config.maxBufferSize = 256000
	} else {
		config.maxBufferSize, _ = strconv.ParseInt(possibleeMaxBufferSize, 10, 64)
	}

	possibleMaxRecords := output.FLBPluginConfigKey(ctx, "maxRecords")
	if len(possibleMaxRecords) == 0 {
		config.maxRecords = 1024
	} else {
		config.maxRecords, _ = strconv.ParseInt(possibleMaxRecords, 10, 64)
	}

	possibleMaxTimeBetweenFlushes := output.FLBPluginConfigKey(ctx, "maxTimeBetweenFlushes")
	if len(possibleMaxTimeBetweenFlushes) == 0 {
		config.maxTimeBetweenFlushes = 5000
	} else {
		config.maxTimeBetweenFlushes, _ =  strconv.ParseInt(possibleMaxTimeBetweenFlushes, 10, 64)
	}

	bufferManager = newBufferManager(config)
	return output.FLB_OK
}
```

**Comment by tanaka-takayoshi** [comment]
Hello, after reading the `out_newrelic.go`, I wonder we should configure Proxy attribute when creating the `&http.Transport`.
https://github.com/newrelic/newrelic-fluent-bit-output/blob/master/out_newrelic.go#L49-L55
```
	defaultTransport := &http.Transport{
		Dial: (&net.Dialer{
			KeepAlive: keepAliveTimeout,
		}).Dial,
		MaxIdleConns:        100,
		MaxIdleConnsPerHost: 100,
	}
```

This is the default Transport for golang.
https://golang.org/src/net/http/transport.go
```
var DefaultTransport RoundTripper = &Transport{
	Proxy: ProxyFromEnvironment,
	DialContext: (&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
		DualStack: true,
	}).DialContext,
	ForceAttemptHTTP2:     true,
	MaxIdleConns:          100,
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
}
```

I wonder we should have to fix as follows.
```
	defaultTransport := &http.Transport{
		Dial: (&net.Dialer{
			KeepAlive: keepAliveTimeout,
		}).Dial,
		MaxIdleConns:        100,
		MaxIdleConnsPerHost: 100,
                Proxy: ProxyFromEnvironment
	}
```

I'll ask a domain expert to review this issue.

**Comment by tetsushiawano** [comment]
Thank you very much!

**Comment by druidsbane** [comment]
We would also find this very useful.  Any chance this support can be added?

**Comment by druidsbane** [comment]
@ngotim @bmcfeely any chance you can take a look at adding that one line mentioned above to enable proxy support for the agent?  It isn't very useful for clusters that don't have open access to the Internet.

**Comment by bmcfeely** [comment]
@druidsbane you bet! Tim and I will see if we can get this prioritized.

**Comment by druidsbane** [comment]
> @druidsbane you bet! Tim and I will see if we can get this prioritized.

Thanks!

**Comment by bmcfeely** [comment]
@druidsbane we got the approval to work on this issue this week. @ngotim will be taking it. Thanks!

**Comment by druidsbane** [comment]
@ngotim hope all is well.  Just a quick ping to see how that is going.  We're using the one-liner fix mentioned above to enable proxies but it would be great for prod to use an official image that has it built-in.  Any chance this can be prioritized for whenever the next release is as that is the only thing holding us back from deploying it in prod?  Thanks!

**Comment by jsubirat** [comment]
Hi @tetsushiawan, @druidsbane , apologies for not coming back to you sooner.

We have added support for HTTP and HTTPS proxies in the following PRs:
* https://github.com/newrelic/newrelic-fluent-bit-output/pull/36
* https://github.com/newrelic/newrelic-fluent-bit-output/pull/41

We have included [a section detailing the proxy support](https://github.com/newrelic/newrelic-fluent-bit-output#proxy-support) in the README.md. You can find additional configuration details in the [Configuration Parameters section](https://github.com/newrelic/newrelic-fluent-bit-output#configuration-parameters).

Thank you for having submitted this feature request!
