### ISSUE TITLE
Upgrade Docker image to FluentBit v1.2+

### ISSUE THREAD

**Issue by AlvinKudos** [newrelic/newrelic-fluent-bit-output#40]
Some log lines in valid JSON format are showing up in New Relic Logs as a JSON encoded string.  So the log lines are not connected to distributed traces nor to applications in APM.

FluentBit v1.2 improves JSON encoding and decoding which should help parsing the log lines so they are more useful in New Relic.  See the [FluentBit v1.2 upgrade notes](https://docs.fluentbit.io/manual/v/1.2/installation/upgrade_notes) for details.

**Comment by jsubirat** [comment]
Hi @AlvinKudos , we updated to Fluent Bit 1.4.5 in this commit: https://github.com/newrelic/newrelic-fluent-bit-output/commit/6d57611fbcc7955cc9088c3825dfc90a2386dc30

Please let us know if the new version fixes your issues. I'm closing this ticket for now.
