### ISSUE TITLE
dockerfile doesn't work: segment violation 

### ISSUE THREAD

**Issue by DanStadlerNewRelic** [newrelic/newrelic-fluent-bit-output#45]
Hi, I just tried out the dockerfile, but it's not working.

Here's my command:
docker run -e "FILE_PATH=/tmp/myfiles*" -e "API_KEY=[redacted]" fb-nr:1.1

Here's my output:

Fluent Bit v1.0.3
Copyright (C) Treasure Data

[2020/06/07 15:40:15] [ warn] [env] variable ${LICENSE_KEY} is used but not set
[2020/06/07 15:40:15] [ info] [storage] initializing...
[2020/06/07 15:40:15] [ info] [storage] in-memory
[2020/06/07 15:40:15] [ info] [storage] normal synchronization mode, checksum disabled
[2020/06/07 15:40:15] [ info] [engine] started (pid=1)
unexpected fault address 0x7ff98692cbf0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7ff98692cbf0 pc=0x7ff986924972]

goroutine 17 [running, locked to thread]:
runtime.throw(0x7ff98692f02d, 0x5)
	/usr/local/go/src/runtime/panic.go:608 +0x74 fp=0xc0000f7bf8 sp=0xc0000f7bc8 pc=0x7ff9865d9324
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x279 fp=0xc0000f7c48 sp=0xc0000f7bf8 pc=0x7ff9865ee569
github.com/fluent/fluent-bit-go/output.FLBPluginSetContext(0x7ff987222030, 0x7ff986a765e0, 0xc00020b3f0)
	/go/src/github.com/fluent/fluent-bit-go/output/output.go:85 +0x92 fp=0xc0000f7c80 sp=0xc0000f7c48 pc=0x7ff986924972
main.FLBPluginInit(0x7ff987222030, 0x7ff986b18750)
	/go/src/github.com/newrelic/newrelic-fluent-bit-output/out_newrelic.go:37 +0x35c fp=0xc0000f7e90 sp=0xc0000f7c80 pc=0x7ff98692c83c
main._cgoexpwrap_664022481967_FLBPluginInit(0x7ff987222030, 0x55dbd4bcbd80)
	_cgo_gotypes.go:62 +0x2d fp=0xc0000f7eb0 sp=0xc0000f7e90 pc=0x7ff98692c2fd
runtime.call32(0x0, 0x7ffd2309a620, 0x7ffd2309a6b0, 0x10)
	/usr/local/go/src/runtime/asm_amd64.s:522 +0x3d fp=0xc0000f7ee0 sp=0xc0000f7eb0 pc=0x7ff9866042bd
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:313 +0x19f fp=0xc0000f7f58 sp=0xc0000f7ee0 pc=0x7ff9865b162f
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:191 +0xdc fp=0xc0000f7fc0 sp=0xc0000f7f58 pc=0x7ff9865b13ec
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/asm_amd64.s:775 +0x9a fp=0xc0000f7fe0 sp=0xc0000f7fc0 pc=0x7ff9866058ca
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000f7fe8 sp=0xc0000f7fe0 pc=0x7ff986606021

**Comment by jsubirat** [comment]
Fixed in https://github.com/newrelic/newrelic-fluent-bit-output/pull/46, many thanks for spotting this! We'll upgrade the K8s related repos now.
