### ISSUE TITLE
OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

### ISSUE THREAD

**Issue by rajumkc** [newrelic/newrelic-fluent-bit-output#59]
I'm trying to add a custom root certificate to the newrelic-fluentbit image by executing the below "docker build" step,  and am running into an OCI Runtime error.

$ docker build --no-cache -t newrelic-fluentbit-output:latest -f- . <<EOF
> FROM newrelic/newrelic-fluentbit-output:1.4.3
> COPY concur-cert.pem .
> COPY concur-cert.pem /usr/local/share/ca-certificates/
> RUN update-ca-certificates --fresh
> EOF
Sending build context to Docker daemon 11.12GB
Step 1/4 : FROM newrelic/newrelic-fluentbit-output:1.4.3
---> 32326c539e3e
Step 2/4 : COPY concur-cert.pem .
---> 25d107be72c7
Step 3/4 : COPY concur-cert.pem /usr/local/share/ca-certificates/
---> b418fb8f8a39
Step 4/4 : RUN update-ca-certificates --fresh
---> Running in 5f4d09d62bd8
OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown

In the "docker inspect" output , I saw:

"Cmd": [
"/bin/sh",
"-c",
"#(nop) ",
"LABEL com.azure.dev.image.system.teamproject=Plugins - Fluent Bit"
]
This tells me that there's a /bin/sh command available.

Please advice on what is causing the OCI runtime error.

**Comment by jsubirat** [comment]
Hi @rajumkc , apologies for coming back to you with so much delay. [Our Docker image is based](https://github.com/newrelic/newrelic-fluent-bit-output/blob/master/Dockerfile#L15) on the Fluent Bit one, which in turn [is based on the distroless images](https://github.com/fluent/fluent-bit/blob/master/dockerfiles/Dockerfile.x86_64#L64). Distroless images do not contain any binary apart from the application binary they execute. This also excludes any shell, that is `sh`. This is why you are receiving the error `"/bin/sh": stat /bin/sh: no such file`.

I assume you need to use a custom root certificate to configure an HTTP proxy, is that correct? In that case, what I'd suggest you is to either copy the certificate inside the image (as you already did) or to mount it externally via a volume, but **do not** run the `update-ca-certificates` command as it seems to be using `sh` internally. Instead, what you can do is to tell our plugin where to find your custom root certificate using the `caBundleFile` or `caBundleDir` configuration options provided by our plugin (see [here](ap-northeast-1)).
