### ISSUE TITLE
newrelic-logging is repeatedly writing [INFO] Request accepted. to stdout

### ISSUE THREAD

**Issue by jmuecke** [newrelic/newrelic-fluent-bit-output#87]
I am a user of the [nri-bundle](https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle) chart, which installs the [newrelic-logging](https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-logging) chart. 

Starting with newrelic-logging-1.5.0 and nri-bundle-2.14.0 the fluentbit container is outputting  `[INFO] Request accepted` around two times per second. I have also tested the most recent version of nri-bundle: 2.20.0 and it still shows the same behavior. 
This causes newrelic-logging to log a lot of data, which is also send to newrelic and thus costing customers money. For our setup this produced around 24GB in less than 24h.

I think, I have tracked this down to the following line: 
https://github.com/newrelic/newrelic-fluent-bit-output/blob/5511fe545433d8b9f7cac90d6ae8e37d9f0208f9/out_newrelic.go#L73

# Suggestion

This should not be logged in INFO but in DEBUG because it only confirms that everything has worked.

**Comment by jodstrcil** [comment]
Hi @jmuecke, thank you for reaching out. I will create a PR immediately.

**Comment by noly** [comment]
Issue was addressed in release [newrelic-fluent-bit-output-1.8.1](https://github.com/newrelic/newrelic-fluent-bit-output/releases/tag/v1.8.1)
